# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # 强制要求在可以加 const 的地方加 const
    prefer_const_constructors: true
    # 当构造函数内部所有属性都是 const 时，建议将构造函数也标记为 const
    prefer_const_constructors_in_immutables: true
    # 强制要求对 const 类型的变量使用 const 声明
    prefer_const_declarations: true
    # 建议对不改变的字面量（如 List, Map）使用 const
    prefer_const_literals_to_create_immutables: true
